version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
  - name: "dim_date"
    description: "data table"
    columns:
      - name: date_key
        description: "Primary key for this table"
        data_tests:
          - unique 
          - not_null
  - name: "dim_customer"
    description: "data table"
    columns:
      - name: customer_id
        description: "Primary key for this table"
        data_tests:
          - unique 
          - not_null
  - name: "dim_staff"
    description: "data table"
    columns:
      - name: staff_id
        description: "Primary key for this table"
        data_tests:
          - unique 
          - not_null
  - name: "dim_store"
    description: "data table"
    columns:
      - name: store_id
        description: "Primary key for this table"
        data_tests:
          - unique 
          - not_null
  - name: "dim_film"
    description: "data table"
    columns:
      - name: film_id
        description: "Primary key for this table"
        data_tests:
          - unique 
          - not_null
sources:
  - name: sakila
    schema: sakila
    tables:
      - name: customer
      - name: address
      - name: city
      - name: country
      - name: staff
      - name: film
      - name: language
      - name: film_category
      - name: category
      - name: store
      - name: rental
      - name: inventory
      - name: payment
